# Generated by Django 3.1.2 on 2020-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideo',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
