# Generated by Django 3.1.2 on 2020-10-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
