# Generated by Django 3.1.2 on 2020-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_auto_20201022_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevideo',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devicevideo',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ytvideo',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
