# Generated by Django 2.2.15 on 2020-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0005_auto_20201015_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevideo',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
