# Generated by Django 2.2.15 on 2020-10-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0006_auto_20201016_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('thumbnail_url', models.URLField()),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
