# Generated by Django 3.1.2 on 2020-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Basic', 'basic'), ('Standard', 'std'), ('Premium', 'prem')], default='basic', max_length=30),
        ),
    ]
